version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: back-end/src/caro-online/Dockerfile
    ports:
      - "5000:8080"
    container_name: caro_backend

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    container_name: caro_frontend
    depends_on:
      - backend
